import html from "html-literal";

export default () => html`
  <main class="main-content">
    <div class="dream-post-container">
      <h1 class="dream-post-title">[PLACEHOLDER]</h1>
      <div class="dream-post-body">
          <p>
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
            [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER] [PLACEHOLDER]
          </p>

        </article>
      </div>

      <div class="comment-section">
        <h1>Comment amount</h1>
        <div>
          <div class="comment">
            <h2 class="anon-comment-name">Anon user</h2>
            <p class="comment-content">comment</p>
          </div>
        </div>
      </div>
    </div>
  </main>
`;
